### ISSUE TITLE
Completion results data missing

### ISSUE THREAD

**Issue by pif** [heathermiller/progfun-stats#1]
Hi, Heather!

This progfun data is awesome!

But I don't see any results data. 
Is it possible to get anonymous course results?

So that we can find answers to questions like 
"How people around the world completed the course?"
"Which country has the highest number of successful students?"
"How many attempts were made, before the successful 10/10 assignment result?"
.. and so on :)

Once more,
Thanks for the course! It was awesome!

**Comment by heathermiller** [comment]
Hi!

You're right, I realized I didn't spend enough time explaining how to access the data. I'll fix that by posting an update to the README shortly! Thanks for bringing it up!

But in the meantime... you've got two choices if you're looking at the data in Scala. You can either import individual fields which represent entire columns in the dataset (i.e. a single question answered by all users) in your Scala object-- for example, to see what all responses were for the question: "What's your highest degree?" you can just do `import CourseraData.degrees` (have a look at [CourseraData.scala](https://github.com/heathermiller/progfun-stats/blob/master/src/main/scala/progfun/CourseraData.scala) to see all possible options). The second option is to `import CourseraData.users`, which is essentially a list of all users' responses, you have access to all answers given an instance of `User`. This is useful in the situation where you want to plot two qualities against each other-- for example, in the graph of perceived difficulty vs background/field ([here](https://github.com/heathermiller/progfun-stats/blob/master/src/main/scala/progfun/ProgfunStats.scala#L95)) we need to know what a single user inputted for two different fields-- in this case, we needed to first filter out only Java/C/C++/FP experts, and then for those users, we needed to examine how difficult they believed the course to be.

Hope that helps!

Cheers,
Heather
