### ISSUE TITLE
SBT 0.12.1

### ISSUE THREAD

**Issue by sergiuszkierat** [heathermiller/progfun-stats#4]
Hi.

There is the issue with sbt 0.12.1

ginger@ginger ~/dev/projects/progfun-stats[master]$ which sbt
/opt/sbt-0.12.1/bin/sbt
ginger@ginger ~/dev/projects/progfun-stats[master]$ sbt
[info] Loading global plugins from /home/ginger/.sbt/plugins
[info] Loading project definition from /home/ginger/Documents/dev/projects/progfun-stats/project
[info] Compiling 1 Scala source to /home/ginger/Documents/dev/projects/progfun-stats/project/target/scala-2.9.2/sbt-0.12/classes...
[error] /home/ginger/Documents/dev/projects/progfun-stats/project/ProgfunStatsBuild.scala:2: object Keys is not a member of package sbt
[error] import sbt.Keys._
[error]            ^
[error] one error found
[error](compile:compile) Compilation failed
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 

I've spent some time to find out about it. Could you verify it yourself?

Regards

**Comment by jozic** [comment]
works for me 

> about
>   [info] This is sbt 0.12.1
>   [info] The current project is {file:/home/jozic/projects/progfun-stats/}progfun-stats
>   [info] The current project is built against Scala 2.9.2
>   [info] Available Plugins: org.sbtidea.SbtIdeaPlugin, sbtassembly.Plugin, sbtdirtymoney.Plugin, com.timushev.sbt.updates.UpdatesPlugin, net.virtualvoid.sbt.graph.Plugin
>   [info] sbt, sbt plugins, and build definitions are using Scala 2.9.2

**Comment by sergiuszkierat** [comment]
I am closing this old one.
